name: deploy fe
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest # 使用 ubuntu 系统镜像运行自动化脚本
    steps: # 自动化步骤
      - name: 签出代码
        uses: actions/checkout@master
      - name: 安装 nodejs
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "16"
      - name: 安装pnpm
        run: npm install pnpm -g
      - name: 安装依赖
        run: pnpm i --no-frozen-lockfile
      - name: 前端项目打包
        run: pnpm build
      - name: Deploy file to Server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.USERNAME }} # 引用配置，用户名称
          server: ${{ secrets.SERVER_IP }} # 引用配置，服务器 IP
          port: ${{ secrets.PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # 引用配置，SSH 私钥
          local_path: 'dist/*'
          remote_path: '/home/ubuntu/st'
